// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.browser.urlbar.matchBuckets", "suggestion:4,general:5");
user_pref("app.normandy.user_id", "496a3545-4263-4a03-9077-6a739cbc234f");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1526246178);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1526281651);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1526245565);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1526246135);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1526282182);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1526246015);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1526281808);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1526245535);
user_pref("browser.laterrun.bookkeeping.sessionCount", 8);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 66);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8a9c26c0-706c-4538-a25d-22b0ba4f6949}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1526256000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1526245987);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1526285211339");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1526287026339");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1526285253349");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1526288853349");
user_pref("browser.search.countryCode", "RU");
user_pref("browser.search.region", "RU");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180509234620");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1526282154");
user_pref("browser.slowStartup.averageTime", 2268);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage", "https://ukmegapolis.bitrix24.ru/stream/");
user_pref("browser.startup.homepage_override.buildID", "20180509234620");
user_pref("browser.startup.homepage_override.mstone", "60.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Яндекс");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1526245542442");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "60.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.lastModified", "Thu, 03 May 2018 19:52:15 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 24);
user_pref("extensions.getAddons.cache.lastUpdate", 1526246179);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180509234620");
user_pref("extensions.lastAppVersion", "60.0");
user_pref("extensions.lastPlatformVersion", "60.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"48cf200d-de05-4222-9a3a-cec81957f2f0\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1526282595);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1526245567);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20180509234620");
user_pref("media.gmp-manager.lastCheck", 1526245566);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1526282595);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("security.sandbox.content.tempDirSuffix", "623b1b38-8f99-4132-ae6a-32f009c05e33");
user_pref("services.blocklist.addons.checked", 1526154104);
user_pref("services.blocklist.clock_skew_seconds", 127546);
user_pref("services.blocklist.gfx.checked", 1526154104);
user_pref("services.blocklist.last_etag", "\"1525377135149\"");
user_pref("services.blocklist.last_update_seconds", 1526154104);
user_pref("services.blocklist.onecrl.checked", 1526154104);
user_pref("services.blocklist.pinning.checked", 1526154104);
user_pref("services.blocklist.plugins.checked", 1526154104);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1526282595);
user_pref("toolkit.startup.last_success", 1526282151);
user_pref("toolkit.telemetry.cachedClientID", "6c5ca24d-63ab-42a2-a0af-6885d2f0bd8b");
user_pref("toolkit.telemetry.previousBuildID", "20180509234620");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
